//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADConversion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCADConversion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///(defun Sub_PrintExtents(Str_FileSaveLocation Str_PrinterName Str_PaperSize Str_CTB )
        ///	(if (= &quot;Model&quot; (getvar &quot;ctab&quot;))
        ///		(command &quot;-plot&quot; &quot;y&quot;  (getvar &quot;ctab&quot;) &quot;DWG To PDF.pc3&quot; Str_PaperSize &quot;Millimeters&quot; &quot;LandScape&quot; &quot;No&quot; &quot;Extents&quot; &quot;Fit&quot; &quot;center&quot; &quot;Yes&quot; Str_CTB &quot;Yes&quot; &quot;As displayed&quot; Str_FileSaveLocation &quot;No&quot;  &quot;Yes&quot;)
        ///		(command &quot;-plot&quot; &quot;y&quot;  (getvar &quot;ctab&quot;) &quot;DWG To PDF.pc3&quot; Str_PaperSize &quot;Millimeters&quot; &quot;LandScape&quot; &quot;No&quot; &quot;Extents&quot; &quot;Fit&quot; &quot;center&quot; &quot;Yes&quot; Str_CTB &quot;Yes&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; Str_FileSaveLocation &quot;No&quot; &quot;Ye [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACADLisp {
            get {
                return ResourceManager.GetString("ACADLisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attdia 1
        ///filedia 1
        ///dwgcheck 1
        ///secureload 0
        ///(load &quot;{0}&quot;)
        ///attdia 0
        ///cmddia 0
        ///filedia 0
        ///dwgcheck 0
        ///.
        /// </summary>
        internal static string AcadScript {
            get {
                return ResourceManager.GetString("AcadScript", resourceCulture);
            }
        }
    }
}
